feat: add support for sha256 hashing
rudderlabs/rudder-workflow-engine pull request #66
Opened 2023-05-15 15:52 UTC by ujjwal-ab

## Description of the change

Add function for hashing to sha256 in common bindings

## Checklists

### Development

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2023-05-15 16:42 UTC, ujjwal-ab commented on src/bindings/common.ts
> +export function toSHA256(text: string | number | undefined) {
Done

2023-05-15 16:42 UTC, ujjwal-ab commented on src/bindings/common.ts
> +import sha256 from 'sha256';
Updated

2023-05-16 03:25 UTC, koladilip requested changes

2023-05-16 03:25 UTC, koladilip commented on src/bindings/common.ts
> +export async function SHA256(text: string | number | undefined) {
Make it sync, using digestSync

2023-05-16 05:53 UTC, ujjwal-ab commented on src/bindings/common.ts
> +export async function SHA256(text: string | number | undefined) {
Done

2023-05-16 06:00 UTC, koladilip approved these changes

2023-05-16 06:12 UTC, sanpj2292 approved these changes

2023-05-16 06:21 UTC, merged